GET https://localhost:4300/api/contatos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlYTFiMzdlMy0wYjI4LTRjMjEtNGYxZS0wOGRjZWUxYjIzODQiLCJlbWFpbCI6InRlc3RlQGdtYWlsLmNvbSIsInVuaXF1ZV9uYW1lIjoidGVzdGUiLCJnaXZlbl9uYW1lIjoibWF0aGV1cyB0ZXN0ZSIsIm5iZiI6MTcyOTc3MjQwMiwiZXhwIjoxNzMwMjA0NDAyLCJpYXQiOjE3Mjk3NzI0MDIsImlzcyI6ImVBZ2VuZGEiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0In0.-5U8HLMmWrxDrrDA3Q8gP7euIYkbuuLODnOsGlyNYJs
